# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNSelectionMenu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'RSSelectionMenu', :git => 'https://github.com/prscX/RSSelectionMenu.git', :branch => 'objc-bridge'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name.include?('RSSelectionMenu')
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.1'
        end
      end
    end
  end
end
